let FailedAssertionError = Exception.extend({
    name = 'FailedAssertionError'

    instance = {
        func raise(self) {
            // TODO: Add the line number
            return raise(self, "Assertion Failed");
        }
    }

    func __construct__(self, _message) {
        self.message = _message;
    }
});

// TODO: Integrate into ParaCode so the condition will be accessible and printable directly
func assert(condition, message) {
    if !condition {
        FailedAssertionError.new(message);
    }
    return condition;
}
